INSERT INTO banks (bank_name, logo) VALUES ('PKO BP', 'logopko.jpg');

INSERT INTO banks (bank_name, logo) VALUES ('Pekao SA', 'logopekao.jpg');
INSERT INTO loans (credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (7.20, 0.0, 'brak', 80, 100000, 120, 18, 15000, 6, 'Expresowa', 13.99, 2);

INSERT INTO banks (bank_name, logo) VALUES ('Millennium', 'logomillennium.jpg');

INSERT INTO banks (bank_name, logo) VALUES ('mBank', 'logombank.jpg');
INSERT INTO loans (credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (7.20, 0.0, 'brak', 70, 180000, 120, 18, 500, 6, 'Standardowa', 12.99, 4);
INSERT INTO loans (credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (7.20, 0.0, 'brak', 70, 180000, 120, 18, 500, 6, 'Standardowa z Kodem', 6.49, 4);
INSERT INTO loans (credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (7.20, 0.0, 'brak', 70, 180000, 120, 18, 500, 6, 'Intensive', 7.99, 4);
INSERT INTO loans (credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (7.20, 0.0, 'brak', 70, 180000, 120, 18, 500, 6, 'Intensive z Kodem', 3.99, 4);
INSERT INTO loans (credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (7.20, 0.0, 'brak', 70, 180000, 120, 18, 500, 6, 'Konsolidacja', 1.99, 4);

INSERT INTO banks (bank_name, logo) VALUES ('BNP', 'logobnp.jpg');
INSERT INTO loans (credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (7.20, 0.0, 'brak', 75, 200000, 120, 18, 1000, 6, 'Uniwersalny', 7.00, 5);
INSERT INTO mortgages (contribution_percent, max_contribution_percent, credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (20.0, 90.0, 2.31, 0.000725, 'mies.', 80, 1000000, 360, 18, 25000, 12, 'Wiosna 2021', 0.0, 5);
INSERT INTO mortgages (contribution_percent, max_contribution_percent, credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (20.0, 90.0, 2.16, 0.000725, 'mies.', 80, 1000000, 360, 18, 25000, 12, 'Bank at Work II', 0.0, 5);

INSERT INTO banks (bank_name, logo) VALUES ('Santander', 'logosantander.jpg');
INSERT INTO loans (credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (7.20, 0.0, 'brak', 80, 200000, 120, 18, 2000, 6, 'Standardowa', 9.99, 6);

INSERT INTO banks (bank_name, logo) VALUES ('BOŚ', 'logobos.jpg');

INSERT INTO banks (bank_name, logo) VALUES ('Alior', 'logoalior.jpg');
INSERT INTO loans (credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (7.19, 0.0, 'brak', 80, 200000, 144, 18, 500, 6, 'Specjalna', 20.90, 8);
INSERT INTO loans (credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (7.19, 0.0, 'brak', 80, 70000, 48, 18, 500, 6, 'Express', 10.99, 8);
INSERT INTO loans (credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (7.19, 0.0, 'brak', 80, 200000, 144, 18, 500, 6, 'Standard', 28.90, 8);
INSERT INTO loans (credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (7.19, 0.0, 'brak', 80, 200000, 144, 18, 500, 6, 'HIP Pożyczka', 17.90, 8);
INSERT INTO loans (credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (7.19, 0.0, 'brak', 80, 200000, 144, 18, 500, 6, 'VIP Pożyczka', 17.90, 8);
INSERT INTO mortgages (contribution_percent, max_contribution_percent, credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (10.0, 90.0, 3.31, 0.00, 'brak', 80, 4000000, 360, 18, 10000, 12, 'Mieszkaniowy z Prowizją', 2.0, 8);
INSERT INTO mortgages (contribution_percent, max_contribution_percent, credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (20.0, 90.0, 3.11, 0.00, 'brak', 80, 4000000, 360, 18, 10000, 12, 'Mieszkaniowy z Prowizją', 2.0, 8);
INSERT INTO mortgages (contribution_percent, max_contribution_percent, credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (10.0, 90.0, 2.81, 0.00, 'brak', 80, 4000000, 360, 18, 10000, 12, 'Własne M w Wielkim Mieście', 2.0, 8);
INSERT INTO mortgages (contribution_percent, max_contribution_percent, credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (20.0, 90.0, 2.61, 0.00, 'brak', 80, 4000000, 360, 18, 10000, 12, 'Własne M w Wielkim Mieście', 2.0, 8);

INSERT INTO banks (bank_name, logo) VALUES ('ING', 'logoing.jpg');
INSERT INTO loans (credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (6.99, 0.0, 'brak', 80, 160000, 120, 18, 1000, 6, 'Bez Ubezpieczenia', 0.0, 9);
INSERT INTO loans (credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (6.99, 0.0, 'brak', 80, 160000, 120, 18, 1000, 6, 'Konsolidacja', 0.0, 9);
INSERT INTO mortgages (contribution_percent, max_contribution_percent, credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (20.0, 80.0, 2.40, 0.00035, 'mies.', 75, 1500000, 360, 18, 100000, 12, 'Promocja Łatwy Start', 0.00, 9);
INSERT INTO mortgages (contribution_percent, max_contribution_percent, credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (20.0, 80.0, 2.16, 0.00035, 'mies.', 75, 1500000, 360, 18, 100000, 12, 'Promocja Lekka Rata', 1.25, 9);
INSERT INTO mortgages (contribution_percent, max_contribution_percent, credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (20.0, 80.0, 2.31, 0.00035, 'mies.', 75, 1500000, 360, 18, 100000, 12, 'Standard Lekka Rata', 1.9, 9);
INSERT INTO mortgages (contribution_percent, max_contribution_percent, credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (20.0, 80.0, 2.61, 0.00035, 'mies.', 75, 1500000, 360, 18, 100000, 12, 'Standard Łatwy Start', 0.00, 9);
INSERT INTO mortgages (contribution_percent, max_contribution_percent, credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (20.0, 80.0, 2.16, 0.00035, 'mies.', 75, 1500000, 360, 18, 100000, 12, 'Ekokredyt', 0.00, 9);

INSERT INTO banks (bank_name, logo) VALUES ('Pocztowy', 'logopocztowy.jpg');
INSERT INTO loans (credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (6.20, 0.0, 'brak', 80, 50000, 120, 18, 2000, 6, 'EKO Cele', 8.0, 10);
INSERT INTO loans (credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (7.20, 0.0, 'brak', 80, 5000, 36, 18, 300, 6, 'Dla Emerytów', 5.0, 10);
INSERT INTO loans (credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (7.20, 0.0, 'brak', 80, 100000, 120, 18, 10000, 6, 'ZOR', 8.0, 10);
INSERT INTO loans (credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (7.20, 0.0, 'brak', 80, 100000, 120, 18, 300, 6, 'Stałej Ceny', 12.0, 10);
INSERT INTO loans (credit_rate, insurance, insurance_frequency, max_borrower_age, max_credit_amount, max_credit_period, min_borrower_age, min_credit_amount, min_credit_period, offer, service_charge, bank_id) VALUES (7.20, 0.0, 'brak', 80, 200000, 120, 18, 100000, 6, 'Stałej Ceny', 12.0, 10);

INSERT INTO banks (bank_name, logo) VALUES ('Getin', 'logogetin.jpg');